name: Metrics
on:
  
  schedule: [{cron: "0 * * * *"}]
 
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: readmetoken
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICREADME }}

          template: classic
          base: header, activity
          config_display: large
          config_timezone: Europe/Istanbul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
